import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Header } from "@/components/general/Header"
import { Sidebar } from "@/components/general/Sidebar"
import { ThemeProvider } from "@/providers/theme-provider"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Gerenciador de Gastos",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<Sidebar />
					<main className="flex md:ml-48 mt-16 p-5 flex-wrap gap-10 overflow-y-auto overflow-x-hidden">
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}
